;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/OrganicLimestone/Content/Localization/OrganicLimestone
DestinationPath=Mods/GameFeatures/OrganicLimestone/Content/Localization/OrganicLimestone
ManifestName=OrganicLimestone.manifest
ArchiveName=OrganicLimestone.archive
ResourceName=OrganicLimestone.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=es

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

